=== ritacamacho/EngWeb2025/Projeto/api/schemas/manifest-sip.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Manifest SIP",
    "type": "object",
    "required": ["id", "author", "createdAt", "items"],
    "properties": {
      "id": {
        "type": "string",
        "format": "uuid"
      },
      "author": {
        "type": "string"
      },
      "createdAt": {
        "type": "string",
        "format": "date-time"
      },
      "items": {
        "type": "array",
        "items": {
          "type": "object",
          "required": ["type", "path"],
          "properties": {
            "type": {
              "type": "string"
            },
            "path": {
              "type": "string"
            },
            "metadata": {
              "type": "object",
              "additionalProperties": true
            }
          }
        }
      }
    },
    "additionalProperties": false
  }

=== ritacamacho/EngWeb2025/Projeto/eu-digital-test/manifest-sip.json
{
  "id": "33333333-3333-3333-3333-333333333333",
  "author": "tester",
  "createdAt": "2025-05-06T12:00:00Z",
  "items": [
    {
      "type": "Photo",
      "path": "Test.svg.png",
      "metadata": {
        "visibility":"private",
        "tags":["test"],
        "caption":"Test.svg.png",
        "format":"png"
      }
    }
  ]
}
